env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
rules:
  no-restricted-imports:
    - error
    - paths:
        - name: "@mui/material"
          message: For small bundle size, import from @mui/material/* instead
      patterns:
        - "!@mui/material/*"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
settings:
  react:
    version: detect
