# To install the git pre-commit hooks run:
#   pre-commit install --install-hooks
# To update the versions:
#   pre-commit autoupdate
# Note the order is intentional to avoid multiple passes of the hooks
exclude: |
  (?x)^(
    yarn\.lock|
    .yarn/.*
  )$
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        language_version: system
        additional_dependencies:
          - prettier
          - "@trivago/prettier-plugin-sort-imports"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.52.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        args:
          - --max-warnings=0
          - --ignore-pattern=!.*.ts
        language_version: system
        additional_dependencies:
          - eslint
          - eslint-plugin-react
          - eslint-plugin-react-hooks
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - react # to “detect” the version
